name: Preview
on: pull_request
jobs:
    preview:
      name: Build
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
        - name: Set up Node
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.OS }}-npm-
              ${{ runner.OS }}-
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Remix auth token
          run: npm config set //npm.remix.run/:_authToken $REMIX_TOKEN
          env:
            REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}
        - name: Install dependencies
          run: npm ci
        - name: Upload to Preview environment
          run: npx wrangler preview --url https://edmund.dev | tee log.out
          env:
            CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        - id: preview
          run: |
            REPORT="$(cat log.out | tail -n 2)"
            REPORT="${REPORT//'%'/'%25'}"
            REPORT="${REPORT//$'\n'/'%0A'}"
            REPORT="${REPORT//$'\r'/'%0D'}"
            echo "::set-output name=result::$REPORT"
        - uses: actions/github-script@v4
          env:
            COMMENT: ${{ steps.preview.outputs.result }}
          with:
            script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.COMMENT,
              })
